# Generated by Django 4.2.9 on 2024-02-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_remove_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_by', models.CharField(max_length=30)),
                ('fromdate', models.CharField(max_length=30)),
                ('todate', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=30)),
            ],
        ),
    ]
