# Generated by Django 4.2.9 on 2024-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0003_leaveapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapply',
            name='apply_by',
            field=models.CharField(max_length=100),
        ),
    ]
