# Generated by Django 4.2.9 on 2024-02-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0004_alter_leaveapply_apply_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapply',
            name='approved_status',
            field=models.IntegerField(default=0),
        ),
    ]
