# Generated by Django 4.2.9 on 2024-02-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0005_leaveapply_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapply',
            name='approved_status_parents',
            field=models.IntegerField(default=0),
        ),
    ]
