# Generated by Django 4.2.9 on 2024-02-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0006_leaveapply_approved_status_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='approved_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default=9284546933, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
