# Generated by Django 4.2.9 on 2024-02-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0007_employee_adhar_image_employee_approved_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(max_length=100),
        ),
    ]
