# Generated by Django 4.2.9 on 2024-02-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0010_alter_employee_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='contact',
        ),
    ]
