# Generated by Django 4.2.9 on 2024-02-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0011_rename_phone_employee_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
