# Generated by Django 4.2.9 on 2024-02-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0012_alter_employee_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact',
        ),
    ]
