# Generated by Django 4.2.9 on 2024-02-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0014_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_by', models.CharField(max_length=100)),
                ('complaint_type', models.CharField(max_length=100)),
                ('sub_complaint_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('note', models.CharField(max_length=1000)),
                ('complaint_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('resolve_status', models.IntegerField(default=0)),
            ],
        ),
    ]
