# Generated by Django 4.2.9 on 2024-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0017_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=100)),
                ('Document_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
    ]
