# Generated by Django 4.2.9 on 2024-02-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0018_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
