# Generated by Django 4.2.9 on 2024-02-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0020_news_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.TextField(max_length=100000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
    ]
