# Generated by Django 4.2.9 on 2024-02-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0021_phone_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_directory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
