# Generated by Django 4.2.9 on 2024-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0024_facility_request_approved_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('semister', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('scorecard_image', models.FileField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
    ]
