# Generated by Django 4.2.9 on 2024-02-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0025_scorecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('approved_status', models.IntegerField(default=0)),
            ],
        ),
    ]
