# Generated by Django 4.2.9 on 2024-04-04 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0027_fine_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine_list',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
