# Generated by Django 4.2.9 on 2024-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0031_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
